version: "3.8"
services:
  app:
    build: /usr/src/app/Demo-nodejs-project
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    - mysql
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo-volume:/data/db
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: DB
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mongo-volume:
  mysql-volume:

